export const EVENTS = {
  ROOM_CREATE: "room:create",
  ROOM_CREATED: "room:created",
  ROOM_JOIN: "room:join",
  ROOM_JOINED: "room:joined",
  ROOM_LEAVE: "room:leave",
  ROOM_STATE: "room:state",
  ROOM_ERROR: "room:error",
  ROOM_CLOSED: "room:closed",

  HOST_CONFIGURE: "host:configure",
  HOST_START: "host:start",
  HOST_START_SURVEY: "host:start-survey",
  HOST_PAUSE: "host:pause",
  HOST_RESUME: "host:resume",
  HOST_STOP: "host:stop",
  HOST_FORCE_NEXT: "host:force-next",
  HOST_SWITCH_MODE: "host:switch-mode",
  HOST_OVERRIDE: "host:override",
  HOST_QUESTION_READY: "host:question-ready",
  HOST_QUIT: "host:quit",
  HOST_END_ALL: "host:end-all",
  HOST_STOP_AI: "host:stop-ai",

  PLAYER_ACCEPT: "player:accept",
  PLAYER_DECLINE: "player:decline",
  PLAYER_ANSWER: "answer:submit",
  SURVEY_SUBMIT: "survey:submit",

  QUESTION_NEW: "question:new",
  TTS_ENDED: "tts:ended",
  TIMER_START: "timer:start",
  ANSWER_REVEAL: "answer:reveal",
  AGENT_LOG: "agent:log",
} as const;
